name = "wedding-website"
main = "worker/index.js"
compatibility_date = "2024-04-01"

# Serve static HTML/CSS/JS frontend alongside the API gateway
[assets]
directory = "."

# Runtime variables
[vars]
GDRIVE_ROOT_FOLDER_ID = "1_JX_WEdxdiBUZ4S1QavDEiqVZJGezPUj"
GDRIVE_FEED_URL = "https://script.google.com/macros/s/AKfycbwfWfy-sgAPreot7OFY1JvRCD-WpfVT_4i7mbuwcJyE5ZDTeZodX5pzH61n4zVLMB3v/exec"
ALLOWED_ORIGIN = "*"
